"use client";
import React,{useEffect,useState} from 'react';
import {MessageCircle,MessagesSquare,Bell,Gift,Megaphone,Plus,Search,ArrowUpRight,ChevronRight,Check,Send,Activity,RotateCcw,Heart,Users,Clock,Calendar,Download} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarContent,SidebarHeader,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Toaster,toast} from 'sonner';
type Row=Record<string,any>;
const modules=[{id:16,name:'Social inquiries',icon:MessageCircle,title:'Every conversation starts here.',desc:'Capture, respond, and turn new inquiries into patient visits.'},{id:17,name:'Patient messaging',icon:MessagesSquare,title:'Connected conversations.',desc:'One history for every patient. Keep the next step clear.'},{id:18,name:'Notifications',icon:Bell,title:'The right update, on time.',desc:'Operational messages, delivery tracking, and reliable follow-through.'},{id:24,name:'Referral & loyalty',icon:Gift,title:'Care worth sharing.',desc:'Manage verified referrals, rewards, and patient loyalty.'},{id:25,name:'Campaigns & engagement',icon:Megaphone,title:'Keep the connection going.',desc:'Thoughtful outreach, patient feedback, and reactivation.'}];
const patients=[{id:'PAT-001',name:'Isabel Reyes',consent:true,last:'2025-12-12'},{id:'PAT-002',name:'Marco Santos',consent:true,last:'2026-08-14'},{id:'PAT-003',name:'Sofia Cruz',consent:false,last:'2025-10-08'},{id:'PAT-004',name:'Ethan Garcia',consent:true,last:'2025-11-20'}];
const seed=()=>({inquiries:[{id:'INQ-1042',name:'Isabel Reyes',source:'Facebook',topic:'Teeth cleaning',contact:'isabel@example.test',staff:'Ana Lopez',status:'New',date:'2026-09-24',messages:[]},{id:'INQ-1041',name:'Marco Santos',source:'Instagram',topic:'Braces consultation',contact:'@marco.demo',staff:'Ana Lopez',status:'Awaiting patient',date:'2026-09-24',messages:[{text:'We can help you schedule a consultation. Which day works for you?',by:'Staff',at:'09:30'}]},{id:'INQ-1040',name:'Sofia Cruz',source:'Facebook',topic:'Clinic hours',contact:'sofia@example.test',staff:'Ben Rivera',status:'Follow-up',date:'2026-09-23',messages:[]},{id:'INQ-1039',name:'Ethan Garcia',source:'Website',topic:'Dental checkup',contact:'ethan@example.test',staff:'Ben Rivera',status:'Closed',date:'2026-09-23',messages:[{text:'Thank you, I will contact you next month.',by:'Patient',at:'14:00'}]}],conversations:[{id:'CON-201',name:'Isabel Reyes',patient:'PAT-001',source:'SMS',staff:'Ana Lopez',status:'Open',messages:[{text:'Hi! Is there anything I need to prepare before my cleaning?',by:'Patient',at:'09:42'},{text:'Hello Isabel! Please bring your appointment confirmation. We’re happy to help with any questions.',by:'Staff',at:'09:45'}]},{id:'CON-202',name:'Marco Santos',patient:'PAT-002',source:'Email',staff:'Ben Rivera',status:'Open',messages:[{text:'Can I move my consultation to Friday?',by:'Patient',at:'10:08'}]}],notifications:[{id:'NTF-301',name:'Isabel Reyes',event:'Appointment confirmation',channel:'SMS',status:'Delivered',text:'Your appointment is confirmed. Please contact the clinic if your plans change.',logs:[{attempt:1,status:'Delivered',at:'09:40',detail:'Demo provider accepted'}]},{id:'NTF-302',name:'Marco Santos',event:'Queue update',channel:'SMS',status:'Failed',text:'Your queue status has changed. Please check with reception.',logs:[{attempt:1,status:'Failed',at:'10:10',detail:'SIMULATED_TIMEOUT'}]}],accounts:patients.map((p,i)=>({...p,code:i===0?'ROX-ISABEL-001':'',points:i===0?150:0})),referrals:[{id:'REF-401',referrer:'Isabel Reyes',referee:'Ethan Garcia',visit:'APT-DEMO-401',status:'Pending',points:0}],transactions:[{id:'TX-001',name:'Isabel Reyes',reason:'Opening demo balance',delta:150,at:'2026-09-20'}],campaigns:[{id:'CMP-501',title:'A little care goes a long way',goal:'Reactivation',group:'Inactive 6+ months',date:'2026-09-26T09:00',text:'It’s been a while! Contact Roxas Dental if you would like to schedule a checkup. Reply STOP to opt out.',status:'Draft',recipients:[],responses:[],feedback:[]}],appointments:[],tasks:[],reward:100,audit:[]});
const key='roxas-engagement-demo-v1';
function Pick({name,label,options,value,onChange}:{name?:string,label:string,options:string[],value?:string,onChange?:(v:string)=>void}){return <label className="field">{label}<Select name={name} value={value} onValueChange={onChange} defaultValue={value?undefined:options[0]}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o} value={o}>{o}</SelectItem>)}</SelectContent></Select></label>}
function Badge({value}:{value:string}){return <span className={'badge '+(/Delivered|Converted|Rewarded|Active|Booked/.test(value)?'green':/Failed|Follow-up/.test(value)?'amber':/New|Open|Scheduled/.test(value)?'blue':'')}>{value}</span>}
function Avatar({name}:{name:string}){return <span className="avatar">{name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span>}
export default function Page(){
 const [data,setData]=useState<any>(seed);const [loaded,setLoaded]=useState(false);const [module,setModule]=useState(16);const [query,setQuery]=useState('');const [filter,setFilter]=useState('All');const [modal,setModal]=useState<any>(null);const [selected,setSelected]=useState('CON-201');const [reply,setReply]=useState('');
 useEffect(()=>{try{const saved=localStorage.getItem(key);if(saved)setData(JSON.parse(saved));}catch{toast.error('Saved demo could not be loaded. A fresh session is ready.')}setLoaded(true)},[]);
 useEffect(()=>{if(loaded)try{localStorage.setItem(key,JSON.stringify(data))}catch{toast.error('Browser storage is full. Changes may not persist.')}},[data,loaded]);
 const current=modules.find(m=>m.id===module)!; const id=(p:string)=>p+'-'+Array.from(crypto.getRandomValues(new Uint8Array(8)),x=>x.toString(16).padStart(2,'0')).join('');const now=()=>new Date().toLocaleString();
 function mutate(fn:(d:any)=>void,message:string){setData((old:any)=>{const d=structuredClone(old);fn(d);d.audit.unshift({at:now(),text:message});return d});toast.success(message)}
 function switchModule(n:number){setModule(n);setFilter('All');setQuery('');setReply('')}
 const inquiry=modal?.id?data.inquiries.find((r:Row)=>r.id===modal.id):null;const conversation=data.conversations.find((r:Row)=>r.id===selected)||data.conversations[0];
 function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));const v=(k:string)=>String(f[k]||'').trim();const type=modal.type;
 if(type==='inquiry'){if(!v('name')||!v('topic'))return;mutate(d=>{d.inquiries.unshift({id:id('INQ'),name:v('name'),contact:v('contact'),source:v('source'),topic:v('topic'),staff:v('staff'),status:'New',date:new Date().toISOString().slice(0,10),messages:[]})},'Inquiry captured and assigned')}
 if(type==='book'){mutate(d=>{const q=d.inquiries.find((r:Row)=>r.id===modal.id);if(q.status==='Converted')return;const a=id('APT');q.status='Converted';q.appointment=a;d.appointments.push({id:a,name:q.name,date:v('date'),service:q.topic,source:q.id});d.conversations.push({id:id('CON'),name:q.name,patient:patients.find(p=>p.name===q.name)?.id||id('PAT'),inquiry:q.id,source:q.source,staff:q.staff,status:'Open',messages:[...q.messages]});d.notifications.unshift({id:id('NTF'),name:q.name,event:'Appointment confirmation',channel:'Email',status:'Delivered',text:`Your demo appointment is scheduled for ${v('date')}.`,logs:[{attempt:1,status:'Delivered',at:now(),detail:'Simulated confirmation'}]})},'Appointment linked; conversation and confirmation created')}
 if(type==='message'){const p=patients.find(p=>p.name===v('patient'))!;mutate(d=>d.conversations.unshift({id:id('CON'),name:p.name,patient:p.id,source:v('channel'),staff:v('staff'),status:'Open',messages:[{text:v('text'),by:'Patient',at:now()}]}),'Incoming message linked to patient')}
 if(type==='event'){const failed=v('result')==='Simulate failure';mutate(d=>d.notifications.unshift({id:id('NTF'),name:v('patient'),event:v('event'),channel:v('channel'),status:failed?'Failed':'Delivered',text:`Hello ${v('patient').split(' ')[0]}, ${v('event').toLowerCase()}: ${v('text')}`,logs:[{attempt:1,status:failed?'Failed':'Delivered',at:now(),detail:failed?'SIMULATED_TIMEOUT':'Demo provider accepted'}]}),'Event processed and delivery status recorded')}
 if(type==='referral'){if(v('referrer')===v('referee')){toast.error('A patient cannot refer themselves');return}const acc=data.accounts.find((a:Row)=>a.name===v('referrer'));if(!acc.code){toast.error('Generate a referral code for this patient first');return}if(data.referrals.some((r:Row)=>r.referee===v('referee'))){toast.error('This patient already has a referral');return}mutate(d=>d.referrals.unshift({id:id('REF'),referrer:v('referrer'),referee:v('referee'),visit:v('visit'),status:'Pending',points:0}),'Referral recorded for qualification')}
 if(type==='redeem'){const amount=Number(v('points')),a=data.accounts.find((a:Row)=>a.name===v('patient'));if(!Number.isInteger(amount)||amount<=0||amount>a.points){toast.error('Enter a positive amount within the available balance');return}mutate(d=>{d.accounts.find((x:Row)=>x.name===a.name).points-=amount;d.transactions.unshift({id:id('TX'),name:a.name,reason:'Reward redemption',delta:-amount,at:now()})},'Redemption recorded; balance updated')}
 if(type==='rules'){mutate(d=>{d.reward=Number(v('points'))},'Pilot reward rule updated')}
 if(type==='campaign'){mutate(d=>d.campaigns.unshift({id:id('CMP'),title:v('title'),goal:v('goal'),group:v('group'),date:v('date'),text:v('text'),status:'Draft',recipients:[],responses:[],feedback:[]}),'Campaign draft created')}
 if(type==='response'){mutate(d=>{const c=d.campaigns.find((r:Row)=>r.id===modal.id);const old=c.responses.find((r:Row)=>r.patient===v('patient'));if(old)old.outcome=v('outcome');else c.responses.push({patient:v('patient'),outcome:v('outcome')});if(v('outcome')==='Booked'&&!d.appointments.some((a:Row)=>a.campaign===c.id&&a.name===v('patient')))d.appointments.push({id:id('APT'),name:v('patient'),campaign:c.id,date:v('date')});c.feedback=c.feedback.filter((r:Row)=>r.patient!==v('patient'));c.feedback.push({patient:v('patient'),rating:Number(v('rating')),text:v('text'),review:Number(v('rating'))<=2})},'Response and feedback recorded')}
 setModal(null);
 }
 const field=(label:string,name:string,type='text',defaultValue?:string)=><label className="field">{label}<input name={name} type={type} required defaultValue={defaultValue} min={type==='number'?1:undefined}/></label>;
 function launch(c:Row){const eligible=patients.filter(p=>p.consent&&(c.group==='All opted-in patients'||new Date(p.last)<new Date(Date.now()-180*86400000)));mutate(d=>{const target=d.campaigns.find((x:Row)=>x.id===c.id);if(target.status==='Active'||target.status==='Closed')return;target.status='Active';target.recipients=eligible.map(p=>p.name);eligible.forEach(p=>d.notifications.unshift({id:id('NTF'),name:p.name,event:'Campaign outreach',channel:'Email',status:'Delivered',campaign:c.id,text:c.text,logs:[{attempt:1,status:'Delivered',at:now(),detail:'Simulated consent-checked campaign'}]}))},`Outreach simulated for ${eligible.length} eligible patients`)}
 function reward(r:Row){if(r.status==='Rewarded'){toast.error('Duplicate reward prevented');return}if(!r.visit){toast.error('A qualifying visit reference is required');return}mutate(d=>{const ref=d.referrals.find((x:Row)=>x.id===r.id);if(d.transactions.some((t:Row)=>t.reference===r.id))return;ref.status='Rewarded';ref.points=d.reward;d.accounts.find((a:Row)=>a.name===r.referrer).points+=d.reward;d.transactions.unshift({id:id('TX'),name:r.referrer,reason:'Verified referral · '+r.visit,delta:d.reward,reference:r.id,at:now()})},'Visit verified in demo; reward applied once')}
 const rows=(module===16?data.inquiries:module===18?data.notifications:[]).filter((r:Row)=>(filter==='All'||r.status===filter)&&JSON.stringify(r).toLowerCase().includes(query.toLowerCase()));
 const stats=module===16?[['Total inquiries',data.inquiries.length,'Across all channels'],['Needs a response',data.inquiries.filter((r:Row)=>['New','Follow-up'].includes(r.status)).length,'Ready for your attention'],['Awaiting patient',data.inquiries.filter((r:Row)=>r.status==='Awaiting patient').length,'Keep the conversation going'],['Booked appointments',data.inquiries.filter((r:Row)=>r.status==='Converted').length,'Linked to inquiry records']]:module===17?[['Conversations',data.conversations.length,'Patient-linked threads'],['Open threads',data.conversations.filter((r:Row)=>r.status==='Open').length,'Awaiting resolution'],['Resolved',data.conversations.filter((r:Row)=>r.status==='Closed').length,'History preserved'],['Messages',data.conversations.reduce((n:number,r:Row)=>n+r.messages.length,0),'Incoming and outgoing']]:module===18?[['Notifications',data.notifications.length,'Operational and campaign'],['Delivered',data.notifications.filter((r:Row)=>r.status==='Delivered').length,'Simulated delivery'],['Failed',data.notifications.filter((r:Row)=>r.status==='Failed').length,'Review and retry'],['Delivery rate',data.notifications.length?Math.round(data.notifications.filter((r:Row)=>r.status==='Delivered').length/data.notifications.length*100)+'%':'—','Calculated from demo records']]:module===24?[['Program members',data.accounts.length,'Sample patient accounts'],['Recorded referrals',data.referrals.length,'Track qualification'],['Rewarded referrals',data.referrals.filter((r:Row)=>r.status==='Rewarded').length,'Duplicate checks enabled'],['Available points',data.accounts.reduce((n:number,r:Row)=>n+r.points,0),'Across all accounts']]:[['Campaigns',data.campaigns.length,'Draft, active, and closed'],['Patients reached',data.campaigns.reduce((n:number,c:Row)=>n+c.recipients.length,0),'Consented outreach records'],['Responses',data.campaigns.reduce((n:number,c:Row)=>n+c.responses.length,0),'Recorded patient outcomes'],['Reactivated',data.campaigns.reduce((n:number,c:Row)=>n+c.responses.filter((r:Row)=>r.outcome==='Booked').length,0),'Follow-up bookings']];
 return <SidebarProvider><Toaster richColors position="bottom-right"/><Sidebar className="clinic-sidebar"><SidebarHeader><div className="brand"><span className="brandmark"><Heart size={24}/></span><div>roxas<span>DENTAL CLINIC</span></div></div></SidebarHeader><SidebarContent><div className="nav-label">PATIENT ENGAGEMENT</div><SidebarMenu>{modules.map(m=><SidebarMenuItem key={m.id}><SidebarMenuButton onClick={()=>switchModule(m.id)} isActive={module===m.id} tooltip={m.name}><m.icon/><span>{m.name}</span>{m.id>20&&<small>PE</small>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="sidebar-note"><span className="tiny-label">A LITTLE MORE CONNECTED</span><h3>Better follow-through.<br/>Better patient care.</h3><p>One workspace, from first hello to the next visit.</p><Heart size={38} strokeWidth={1}/></div></SidebarContent><SidebarFooter><div className="staff"><Avatar name="Ana Lopez"/><div><strong>Ana Lopez</strong><span>Clinic staff · Demo</span></div></div></SidebarFooter></Sidebar><SidebarInset><header className="topbar"><div><SidebarTrigger/><span>Workspace</span><ChevronRight size={14}/><strong>{current.name}</strong></div><span className="demo-pill">Demo workspace</span></header><main><div className="eyebrow">PATIENT ENGAGEMENT <span>/ MODULE {module}</span>{module>20&&<Badge value="Proposed Enhancement"/>}</div><div className="page-heading"><div><h1>{current.title}</h1><p>{current.desc}</p></div><button className="primary" onClick={()=>setModal({type:module===16?'inquiry':module===17?'message':module===18?'event':module===24?'referral':'campaign'})}><Plus size={17}/>{module===16?'New inquiry':module===17?'Receive message':module===18?'Simulate event':module===24?'Record referral':'Create campaign'}</button></div><div className="stats">{stats.map(([label,value,sub],i)=><section className="stat" key={label}><div>{label}{i===0?<Users size={17}/>:i===1?<Clock size={17}/>:i===2?<MessageCircle size={17}/>:<Activity size={17}/>}</div><strong>{value}</strong><span>{sub}</span></section>)}</div>
 {module===16&&<div className="workspace-grid"><section className="panel"><div className="panel-head"><div><h2>Inquiry inbox <span className="count">{data.inquiries.length}</span></h2><p>Every new hello, in one place.</p></div></div><div className="filters"><Tabs value={filter} onValueChange={setFilter}><TabsList>{['All','New','Follow-up','Converted'].map(v=><TabsTrigger value={v} key={v}>{v}</TabsTrigger>)}</TabsList></Tabs><label className="search"><Search size={16}/><input aria-label="Search inquiries" placeholder="Search inquiries…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><Table><TableHeader><TableRow>{['Patient / inquiry','Channel','Assigned to','Status',''].map((t,i)=><TableHead key={i}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((r:Row)=><TableRow key={r.id}><TableCell><button className="person" onClick={()=>setModal({type:'detail',id:r.id})}><Avatar name={r.name}/><span><strong>{r.name}</strong><small>{r.topic}</small></span></button></TableCell><TableCell><span className={'channel '+r.source.toLowerCase()}>{r.source.slice(0,1)}</span>{r.source}</TableCell><TableCell>{r.staff}</TableCell><TableCell><Badge value={r.status}/></TableCell><TableCell><button className="icon-button" aria-label={'Open '+r.name} onClick={()=>setModal({type:'detail',id:r.id})}><ArrowUpRight size={18}/></button></TableCell></TableRow>)}</TableBody></Table>{!rows.length&&<div className="empty">No inquiries match your search.</div>}<div className="panel-foot">Showing {rows.length} inquiries <span>Sample patient data</span></div></section><aside className="right-column"><section className="focus-card"><span className="tiny-label"><Clock size={15}/> FOLLOW-UP FOCUS</span><h2>A timely reply<br/>makes a difference.</h2><p>{data.inquiries.filter((r:Row)=>['New','Follow-up'].includes(r.status)).length} inquiries need your attention. Pick up where the patient left off.</p><button onClick={()=>setFilter('Follow-up')}>View follow-ups <ArrowUpRight size={16}/></button></section><section className="panel source-panel"><h2>Where patients find us</h2><p>Inquiries by source</p>{['Facebook','Instagram','Website'].map(s=>{const n=data.inquiries.filter((r:Row)=>r.source===s).length;return <div className="source-row" key={s}><div><span>{s}</span><strong>{n}</strong></div><div className="bar"><i style={{width:(n/data.inquiries.length*100||0)+'%'}}/></div></div>})}</section></aside></div>}
 {module===17&&<section className="panel messages"><div className="thread-list"><h2>Conversations</h2>{data.conversations.map((c:Row)=><button key={c.id} className={'thread '+(conversation?.id===c.id?'selected':'')} onClick={()=>{setSelected(c.id);setReply('')}}><Avatar name={c.name}/><span><strong>{c.name}</strong><small>{c.messages.at(-1)?.text||'No messages'}</small><Badge value={c.status}/></span></button>)}</div>{conversation&&<div className="chat"><div className="chat-head"><div><h2>{conversation.name}</h2><p>{conversation.patient} · {conversation.source}</p></div><button className="secondary" onClick={()=>mutate(d=>{const c=d.conversations.find((c:Row)=>c.id===conversation.id);c.status=c.status==='Closed'?'Open':'Closed'},conversation.status==='Closed'?'Conversation reopened':'Conversation resolved; history preserved')}>{conversation.status==='Closed'?'Reopen':'Resolve conversation'}</button></div><div className="route"><Pick label="Assigned staff" value={conversation.staff} options={['Ana Lopez','Ben Rivera']} onChange={v=>mutate(d=>{d.conversations.find((c:Row)=>c.id===conversation.id).staff=v},'Conversation routed')}/><Badge value={conversation.status}/></div><div className="chat-history">{conversation.messages.map((m:Row,i:number)=><div className={'bubble '+(m.by==='Staff'?'outgoing':'')} key={i}><span>{m.by}</span><p>{m.text}</p><small>{m.at} · {m.by==='Staff'?'Recorded':'Received'}</small></div>)}</div><form className="composer" onSubmit={e=>{e.preventDefault();if(!reply.trim())return;mutate(d=>d.conversations.find((c:Row)=>c.id===conversation.id).messages.push({text:reply.trim(),by:'Staff',at:now()}),'Reply recorded and history updated');setReply('')}}><button type="button" className="text-button" disabled={conversation.status==='Closed'} onClick={()=>setReply('Thank you for reaching out. We will check availability and get back to you shortly.')}>Use reply template</button><textarea aria-label="Write a reply" placeholder="Write a thoughtful reply…" value={reply} onChange={e=>setReply(e.target.value)} disabled={conversation.status==='Closed'}/><div><small>Demo: replies stay in this browser.</small><button className="primary" disabled={!reply.trim()||conversation.status==='Closed'}><Send size={16}/>Record reply</button></div></form></div>}</section>}
 {module===18&&<section className="panel"><div className="panel-head"><div><h2>Notification activity</h2><p>Delivery attempts are logged before every retry.</p></div><Tabs value={filter} onValueChange={setFilter}><TabsList>{['All','Delivered','Failed'].map(v=><TabsTrigger key={v} value={v}>{v}</TabsTrigger>)}</TabsList></Tabs></div><Table><TableHeader><TableRow>{['Patient','Event','Channel','Delivery','Attempts','Action'].map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((r:Row)=><TableRow key={r.id}><TableCell><strong>{r.name}</strong><small className="block">{r.id}</small></TableCell><TableCell>{r.event}</TableCell><TableCell>{r.channel}</TableCell><TableCell><Badge value={r.status}/></TableCell><TableCell>{r.logs.length}</TableCell><TableCell><button className="text-button" onClick={()=>setModal({type:'logs',id:r.id})}>View history</button>{r.status==='Failed'&&<button className="secondary" onClick={()=>mutate(d=>{const n=d.notifications.find((x:Row)=>x.id===r.id);n.logs.push({attempt:n.logs.length+1,status:'Delivered',at:now(),detail:'Simulated retry accepted'});n.status='Delivered'},'Retry delivered; attempt history preserved')}><RotateCcw size={14}/>Retry</button>}</TableCell></TableRow>)}</TableBody></Table>{!rows.length&&<div className="empty">No notifications in this view.</div>}</section>}
 {module===24&&<><div className="enhancement"><Gift size={19}/><div><strong>Proposed Enhancement · Optional pilot</strong><p>Demo rule: {data.reward} points per verified referral. Reward eligibility is clinic-configured.</p></div><button className="secondary" onClick={()=>setModal({type:'rules'})}>Edit reward rule</button></div><div className="loyalty-grid"><section className="panel"><div className="panel-head"><h2>Loyalty accounts</h2><button className="text-button" onClick={()=>setModal({type:'redeem'})}>Redeem points <ArrowUpRight size={15}/></button></div>{data.accounts.map((a:Row)=><div className="account" key={a.id}><Avatar name={a.name}/><div><strong>{a.name}</strong><small>{a.code||'No referral code yet'}</small></div><strong className="points">{a.points}<small>points</small></strong>{!a.code&&<button className="secondary" onClick={()=>mutate(d=>{d.accounts.find((x:Row)=>x.id===a.id).code='ROX-'+a.id},'Unique referral code generated')}>Generate code</button>}</div>)}</section><section className="panel"><div className="panel-head"><h2>Referral qualification</h2></div>{data.referrals.map((r:Row)=><div className="referral" key={r.id}><div><strong>{r.referrer} <ChevronRight size={14}/> {r.referee}</strong><small>Qualifying visit: {r.visit}</small></div><Badge value={r.status}/><button className="secondary" onClick={()=>reward(r)}>{r.status==='Rewarded'?'Check duplicate protection':'Verify visit & award'}</button></div>)}</section></div><section className="panel history"><div className="panel-head"><h2>Loyalty transaction history</h2></div>{data.transactions.map((t:Row)=><div className="history-row" key={t.id}><div><strong>{t.name}</strong><small>{t.reason} · {t.at}</small></div><strong className={t.delta>0?'positive':''}>{t.delta>0?'+':''}{t.delta} pts</strong></div>)}</section></>}
 {module===25&&<><div className="enhancement"><Megaphone size={19}/><div><strong>Proposed Enhancement · Consent-aware outreach</strong><p>Only opted-in patients matching the target group receive demo outreach. Operational updates stay separate.</p></div></div><div className="campaign-grid">{data.campaigns.map((c:Row)=><section className="panel campaign" key={c.id}><div className="campaign-top"><span className="campaign-icon"><Megaphone size={23}/></span><Badge value={c.status}/></div><span className="tiny-label">{c.goal}</span><h2>{c.title}</h2><p>{c.text}</p><div className="campaign-meta"><span><Users size={15}/>{c.group}</span><span><Calendar size={15}/>{c.date.replace('T',' · ')}</span></div><div className="campaign-numbers"><div><strong>{c.recipients.length}</strong><small>Reached</small></div><div><strong>{c.responses.length}</strong><small>Responses</small></div><div><strong>{c.responses.filter((r:Row)=>r.outcome==='Booked').length}</strong><small>Reactivated</small></div></div><div className="actions">{c.status==='Draft'&&<button className="secondary" onClick={()=>mutate(d=>{d.campaigns.find((x:Row)=>x.id===c.id).status='Scheduled'},'Outreach scheduled in demo')}>Schedule outreach</button>}{['Draft','Scheduled'].includes(c.status)&&<button className="primary" onClick={()=>launch(c)}>Simulate outreach <Send size={15}/></button>}{c.status==='Active'&&<><button className="primary" disabled={!c.recipients.length} onClick={()=>setModal({type:'response',id:c.id})}>Record response</button><button className="secondary" onClick={()=>mutate(d=>{d.campaigns.find((x:Row)=>x.id===c.id).status='Closed'},'Campaign closed; performance summary preserved')}>Close campaign</button></>}</div>{c.feedback.map((f:Row)=><div className="feedback" key={f.patient}><strong>{f.patient} · {f.rating}/5</strong><p>{f.text||'No written comment'}</p>{f.review&&<Badge value="Management review needed"/>}</div>)}</section>)}</div></>}
 <footer><span><span className="demo-dot"/> Interactive demo · Changes saved in this browser</span><div><button onClick={()=>setModal({type:'activity'})}>Activity history</button><button onClick={()=>setModal({type:'reset'})}>Reset demo</button></div></footer></main></SidebarInset>
 <Dialog open={!!modal} onOpenChange={o=>!o&&setModal(null)}><DialogContent className="demo-dialog"><DialogTitle>{({inquiry:'Capture a new inquiry',detail:inquiry?.name,book:'Convert to appointment',message:'Receive a patient message',event:'Simulate an operational event',logs:'Notification delivery history',referral:'Record a referral',redeem:'Redeem loyalty points',rules:'Configure pilot reward',campaign:'Create an engagement campaign',response:'Record response & feedback',reset:'Reset this demo?',activity:'Workspace activity'} as any)[modal?.type]||'Details'}</DialogTitle><DialogDescription>{modal?.type==='reset'?'This clears your demo changes and restores the sample records.':'Sample data only. External messages and visit verification are simulated.'}</DialogDescription>
 {modal?.type==='detail'&&inquiry&&<><div className="detail-meta"><Badge value={inquiry.status}/><span>{inquiry.id} · {inquiry.source}</span></div><p><strong>{inquiry.topic}</strong><br/>{inquiry.contact}</p><Pick label="Responsible staff" value={inquiry.staff} options={['Ana Lopez','Ben Rivera']} onChange={v=>mutate(d=>{d.inquiries.find((r:Row)=>r.id===inquiry.id).staff=v},'Inquiry reassigned')}/>{inquiry.messages.map((m:Row,i:number)=><div className="bubble" key={i}><small>{m.by} · {m.at}</small><p>{m.text}</p></div>)}{!['Closed','Converted'].includes(inquiry.status)&&<><label className="field">Staff response<textarea value={reply} onChange={e=>setReply(e.target.value)}/></label><div className="actions"><button className="primary" disabled={!reply.trim()} onClick={()=>{mutate(d=>{const q=d.inquiries.find((r:Row)=>r.id===inquiry.id);q.messages.push({text:reply.trim(),by:'Staff',at:now()});q.status='Awaiting patient'},'Staff response recorded');setReply('')}}>Record response</button><button className="secondary" onClick={()=>mutate(d=>{const q=d.inquiries.find((r:Row)=>r.id===inquiry.id);q.status='Follow-up';if(!d.tasks.some((t:Row)=>t.inquiry===q.id))d.tasks.push({inquiry:q.id,staff:q.staff,task:'Follow up unanswered inquiry'})},'Follow-up task created')}>Create follow-up</button><button className="secondary" onClick={()=>setModal({type:'book',id:inquiry.id})}>Book appointment</button><button className="text-button" onClick={()=>mutate(d=>{d.inquiries.find((r:Row)=>r.id===inquiry.id).status='Closed'},'Inquiry closed')}>Close inquiry</button></div></>}{inquiry.appointment&&<p className="enhancement">Linked appointment: {inquiry.appointment}</p>}</>}
 {modal?.type==='logs'&&(()=>{const n=data.notifications.find((n:Row)=>n.id===modal.id);return <><p>{n.text}</p>{n.logs.map((l:Row)=><div className="history-row" key={l.at+l.attempt}><div><strong>Attempt {l.attempt} · {l.status}</strong><small>{l.at} · {l.detail}</small></div></div>)}</>})()}
 {modal?.type==='activity'&&<>{data.audit.length?data.audit.map((a:Row,i:number)=><div className="history-row" key={i}><div><strong>{a.text}</strong><small>{a.at}</small></div></div>):<p>No actions yet. Try capturing an inquiry.</p>}<h3>Appointment links</h3>{data.appointments.map((a:Row)=><p key={a.id}>{a.id} · {a.name} · {a.date}</p>)}</>}
 {modal?.type==='reset'&&<button className="primary" onClick={()=>{setData(seed());setModal(null);toast.success('Sample data restored')}}>Reset sample data</button>}
 {modal&&!['detail','logs','reset','activity'].includes(modal.type)&&<form onSubmit={submit} className="modal-form">
 {modal.type==='inquiry'&&<>{field('Patient / sender name','name')}{field('Contact or social handle','contact')}{field('Inquiry topic','topic')}<Pick name="source" label="Inquiry source" options={['Facebook','Instagram','Website']}/><Pick name="staff" label="Assign to" options={['Ana Lopez','Ben Rivera']}/></>}
 {modal.type==='book'&&<>{field('Appointment date and time','date','datetime-local')}<p>A conversation and simulated appointment confirmation will be linked automatically.</p></>}
 {['message','event','redeem'].includes(modal.type)&&<Pick name="patient" label="Patient" options={patients.map(p=>p.name)}/>}
 {modal.type==='message'&&<><Pick name="channel" label="Channel" options={['SMS','Email','Facebook','Instagram']}/><Pick name="staff" label="Route to" options={['Ana Lopez','Ben Rivera']}/>{field('Incoming patient message','text')}</>}
 {modal.type==='event'&&<><Pick name="event" label="System event" options={['Appointment confirmation','Appointment reminder','Rescheduling notice','Queue update','Wait-time update','Delay notice','Follow-up reminder']}/><Pick name="channel" label="Delivery channel" options={['SMS','Email']}/>{field('Event details for patient','text')}<Pick name="result" label="Demo delivery result" options={['Simulate success','Simulate failure']}/></>}
 {modal.type==='referral'&&<><Pick name="referrer" label="Referring patient" options={patients.map(p=>p.name)}/><Pick name="referee" label="Referred patient" options={patients.map(p=>p.name)}/>{field('Qualifying completed visit reference','visit')}<p>Verification is manual in this demo; production must validate appointment and billing records.</p></>}
 {['redeem','rules'].includes(modal.type)&&field(modal.type==='rules'?'Points per qualified referral':'Points to redeem','points','number',modal.type==='rules'?String(data.reward):undefined)}
 {modal.type==='campaign'&&<>{field('Campaign title','title')}<Pick name="goal" label="Campaign goal" options={['Reactivation','Patient education','Feedback collection']}/><Pick name="group" label="Target patient group" options={['Inactive 6+ months','All opted-in patients']}/>{field('Outreach date and time','date','datetime-local')}<label className="field">Outreach message<textarea name="text" required defaultValue="Hello! Contact Roxas Dental if you would like to schedule a checkup. Reply STOP to opt out."/></label><p>Outreach runs only when you choose “Simulate outreach”; there is no background scheduler in this UI demo.</p></>}
 {modal.type==='response'&&<><Pick name="patient" label="Reached patient" options={data.campaigns.find((c:Row)=>c.id===modal.id).recipients}/><Pick name="outcome" label="Response outcome" options={['Interested','Booked','Declined','No response']}/>{field('Follow-up date (used if booked)','date','datetime-local')}<Pick name="rating" label="Feedback rating" options={['5','4','3','2','1']}/><label className="field">Feedback comment<textarea name="text"/></label></>}
 <button className="primary" type="submit">{modal.type==='event'?'Process demo event':modal.type==='book'?'Confirm demo booking':'Save record'}<Check size={16}/></button></form>}
 </DialogContent></Dialog></SidebarProvider>
}
